# Basic info
site_name: Michael Qiu's Blog
site_author: Michael Qiu
site_description: This is Michael Qiu's personal site.
site_url: https://gitmichaelqiu.github.io

# Repository
repo_name: 'gitmichaelqiu.github.io'
repo_url: 'https://github.com/gitmichaelqiu/gitmichaelqiu.github.io'

# Content
nav:
  - Home:
    - About: index.md
    - Some Websites: some-websites.md
    - Utilities:
      - Discord Spam Spoiler: utilities/discord-spam-spoiler.md

  - My Projects:
    - My Projects: my-projects/my-projects.md
    - LexiGen:
      - LexiGen: my-projects/lexigen/lexigen.md
      - Keyboard Shortcuts: my-projects/lexigen/keyboard-shortcuts.md
      - Customize Prompts: my-projects/lexigen/customize-prompts.md

  - Algorithms:
    - GCD & LCM: algorithms/gcd-lcm.md
    - Prime:
      - Euler Sieve: algorithms/prime/euler-sieve.md
    - Search:
      - A*: algorithms/search/a-star.md
    - Shortest Path:
      - Bellman Ford: algorithms/shortest-path/bellman-ford.md
      - Dijkstra (prioirty_queue): algorithms/shortest-path/dijkstra.md
      - Floyd: algorithms/shortest-path/floyd.md
      - SPFA: algorithms/shortest-path/spfa.md
    - Sort:
      - Sort Overview: algorithms/sort/sort-overview.md
      - Bubble Sort: algorithms/sort/bubble-sort.md
      - Radix Sort: algorithms/sort/radix-sort.md
    - Quick Pow: algorithms/quick-pow.md
    
  - Data Structures:
    - Bignum: data-structures/bignum.md
    - Binary Heap: data-structures/binary-heap.md
    - Disjoint Set Union: data-structures/disjoint-set-union.md
    - Segment Tree: data-structures/segment-tree.md
    - Sparse Table: data-structures/sparse-table.md
    - Stack: data-structures/stack.md
    - Tree:
      - Binary Tree Traversals: data-structures/tree/binary-tree-traversals.md
      
  - OI Tips:
    - Elapsed Time Measurement: oi-tips/elapsed-time.md
    - File Read & Write: oi-tips/file-read-and-write.md
    - GCC Optimize: oi-tips/gcc-optimize.md
    - iostream Acceleration: oi-tips/accelerate-ios.md
    - Quick Read & Write: oi-tips/qread-and-qwrite.md
    
  - Academic Notes:
    - AP:
      - Calculus:
        - Limit: academic-notes/ap/calculus/limit.md
        - Differentiation: academic-notes/ap/calculus/differentiation.md
        - Fundamental Calculus: academic-notes/ap/calculus/fundamental-calculus.md
      - Microeconomics:
        - Basic Economic Concept: academic-notes/ap/microeconomics/basic-economic-concept.md
        - Demand and Supply: academic-notes/ap/microeconomics/demand-and-supply.md
        - Production, Cost and Competition: academic-notes/ap/microeconomics/production-cost-and-competition.md
    - Chinese:
      - 初中:
        - 初中地理总结: academic-notes/chinese/junior-notes/geography.md
      - 高中:
        - 集合: academic-notes/chinese/senior-high-school/sets.md
        - 抛物线运动: academic-notes/chinese/senior-high-school/projectile-motion.md
  - Blog:
    - blog/index.md

# Appearance
theme:
  name: material

  logo: assets/logo-MK-round-circle-auto.svg
  favicon: images/favicon.png
  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    # - navigation.indexes

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/auto-mode
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - toc:
      baselevel: 2
      toc_depth: 4 
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gitmichaelqiu

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

plugins:
  - search
  - blog
  - mkdocs-audio
  - mkdocs-video
  - embed_file
  # - social
  - git-revision-date-localized:
      type: date