[project]
site_name = "My site"
site_url = "https://gitmichaelqiu.github.io"
site_description = "Michael Qiu's personal website."
site_author = "Michael Y. Qiu"
copyright = "&copy; 2025 Michael Y. Qiu"
docs_dir = "docs"
site_dir = "site"